# English names for Sights/experience rows whose names were machine-romanised Japanese.
# Translated from each row's own source page title (titles.json); official English names used where they exist.
OLDMAP = "Old-Map Town Walk"
EN = {
1:"Isedotai Stone Circles", 2:"Akita Maiko and Akita Geisha", 3:"Dormy Inn Akita (Nakadori Onsen Komachi no Yu)",
4:"Akita Prefectural Skating Rink", 5:"Garo Falls and Garo Gorge", 6:"Roadside Station Tenno Green Land",
7:"Health Walk with Akita Dogs", 8:"Masuda Tourist Information Center", 9:"Yurihonjo Folk Performing Arts Hall (Maiire)",
10:"Genji no Mori Nature Study Village (Genji no Mori Onsen)", 11:"Ashiya Town Tourism Association",
12:"Giant Chair & Desk", 13:"Clam Digging at Unoshima Coast", 14:"Shiida Agri Park (Farm Park)",
15:"Shiida Plum Festival (Tsunashiki Tenmangu Shrine)", 16:"Sumiyoshi Shrine, Chikuzen's First Shrine",
17:"Sazae-san Shopping Street", 18:"Country Farm Kiichigo-sha (Blueberry Farm)", 19:"Hakata Mizuhiki Cord Craft",
20:"Shinbaru-Nuyama Burial Mounds (World Heritage)", 21:"Koshio Terraced Fields", 22:"The Retreat (Iizuka)",
23:"Okuma Castle Ruins (Masutomi Castle Ruins)", 24:"Hygge Experience in the Forest", 25:"Tonokawa Green Park Cherry Blossoms",
26:"Kasuga Nishi Multipurpose Park (Shinkansen Viewpoint)", 27:"Utoguchi Tile Kiln Exhibition Hall (Climbing Kiln Plaza)",
28:"Mizuki Castle Ruins", 29:"Rokujusshaku Iron Bridge (Second Onga River Bridge)", 30:"Kawasaki Farm Produce Market De-Ai",
31:"Hibikinada Green Park", 32:"Higashida First Blast Furnace Historic Site", 33:"Former 130th Bank Gallery",
34:"Yellow Banana Postbox, Mojiko Retro", 35:"Mushirouchi Rape Blossom Fields", 36:"Hamabo Hibiscus Blossoms",
37:"Kyushu Olle Miyama-Kiyomizuyama Course Autumn Walk", 38:"Kyushu Olle Miyama-Kiyomizuyama Course",
39:"Nanohana Batake Fresh Food Market", 40:"Onga River Waterside Hall", 41:"Ajisaka Poppy Fields (Poppy Festival)",
42:"Hokkori Farm (Food Education Farm)", 43:"Red-Brick Arch, One of Kyushu's Oldest Railway Structures",
44:"Oki Recycling Center Kururun", 45:"Miike Coal Mine Mikawa Pit Ruins", 46:"Omuta City Miike Karuta & History Museum",
47:"Tram No. 204 Cafe (hara harmony coffee)", 48:"Omuta City Zoo One-Day Keeper Experience", 49:"Miike Coal Mine Railway Ruins",
50:"Oak Leaf (Kaho Daifuku Main Shop)", 51:"Tanko-bushi Sweets (Kashi no Ito)", 52:"Salmon Release Event (Onga Town)",
53:"Sasaguri Forest Therapy Base", 54:"Ajisai Road (Sasaguri Forest Therapy)", 55:"Kyushu Olle Shingu-Tachibana Course",
56:"Copper Torii of Hikosan Jingu Shrine", 57:"Former Mitsui Tagawa Mine Ita Pit Chimneys", 58:"Ponta no Mori Campground",
59:"Chikugo-Yoshii White-Wall Streetscape", 60:"Yame-Fukushima White-Wall Streetscape", 61:None,
62:"Nakaniida Bach Hall", 63:None, 64:None, 65:None, 66:"Zao Dairy Center Cheese Cabin", 67:None, 68:None,
69:"Suginoi Hotel Aqua Beat (Beppu Onsen)", 70:"Shibai no Yu Public Bath (Beppu Community Center)",
71:"Ta no Yu Public Onsen", 72:"B-Con Plaza (Beppu International Convention Center)", 73:"Beppu Arena (Beppu City Gymnasium)",
74:"Kyushu Olle Oku-Bungo Course", 75:"Konaido Scenery along the Ono River", 76:"Museum of Heterogeneous Nature and People",
77:"Nameshi Dam Green Land (Cotton Village)", 78:"Oita Himeshima Geopark", 79:"Kanoya Restaurant (Himeshima)",
80:"Himeshima Port (Village Ferry Terminal)", 81:"Kokonoe Yume Onsen Area", 82:"Kokonoe Yume Otsurihashi Suspension Bridge",
83:"Yayoi no Mura Kunisaki History Experience Center", 84:"Gallery Takumi no Sato Hana (Stone Buddha Carving)",
85:"Nishishiiya Falls", 86:"Yabakei Scenic Route (Japan Heritage)", 87:"Yabakei Scenic Route (Japan Heritage)",
88:"Oita Country Club Tsukigata Course", 89:"Sasamuta Shrine", 90:"Ferry Sunflower West Oita Port",
91:"Kyushu Olle Saiki-Oniujima Course", 92:"Kuju Water Fairyland Craft Beer Village", 93:"Aotake Workshop Kiriyama",
94:"Kuju Winery Restaurant & Stone-Oven Workshop", 95:"Shichirida Onsen Konoha no Yu", 96:"Sasamuta Stone Aqueduct Bridge",
97:"Meisei Irrigation First Stone Arch Bridge (Six-Arch Aqueduct)", 98:"Tsukumi Dolphin Island", 99:"Ajimu Little Wine Workshop",
100:"Higashishiiya Falls", 101:"Nishishiiya Scenery (Machu Picchu of Usa)", 102:"Daijo-in Temple Demon Mummy",
103:"Chikko Sai Gallery Saisa", 104:"Hacchoji Street (Usuki Chuo-dori Shopping Street)", 105:"Unagihime Shrine",
106:"Fukuga Agriculture Festival 2026", 107:"Kitaura Coast (Nago to Utagō)", 108:"Fukuga Carp Streamers",
109:OLDMAP+": Hagi Castle Town", 110:"Hagi World Heritage Bingo Rally 2026", 111:"Old-School Day at Hagi Meirin Gakusha Wooden Schoolhouse",
112:"Hagi Hakkei Sightseeing Boat (Sunset Course)", 113:OLDMAP+": Hagi Castle Ruins", 114:"Hagi Hakkei Sightseeing Boat (World Heritage & Geopark HAPPINESS Course)",
115:"Hagi Hakkei Sightseeing Boat (Sea of Japan Course)", 116:OLDMAP+": Horiuchi (Easy Course Available)",
117:OLDMAP+" (Limited Time): Onari-machi, Fudaba and Tamachi Shopping Street, Hagi", 118:"NPO Hagi Tourist Guide Association",
119:OLDMAP+": Susa", 120:OLDMAP+" (Limited Time): Teramachi Merchant Quarter, Hagi", 121:OLDMAP+": Hamasaki",
122:OLDMAP+" (Limited Time): Aidama-za, Hagi", 123:OLDMAP+": Sasanami-ichi", 124:"Castle Town Special Experience: Turning the Gears of Time",
125:OLDMAP+" (Limited Time): Hagi Castle Honmaru, Ninomaru and Sannomaru", 126:OLDMAP+" (Limited Time): Kumaya Merchant House, Hagi",
127:"Hagi Stroll by E-Scooter in Kimono", 128:"Hagi Hakkei Sightseeing Boat (Cherry Blossom Course)", 129:"NPO Hagi Machiju Museum Old-Map Guide Team",
130:"Hagi Hakkei Sightseeing Boat (Cherry Blossom & Autumn Leaves Course)", 131:"FURUSATO Cycling by E-Bike (Castle Town Course)",
132:"Hagi-yaki Pottery Class with a Master Craftsman", 133:"Make a Lampshade from Hagi Bamboo Paper",
134:"Mishima Jikonbo Burial Mounds", 135:"Toita Masuda Family Former Residence Earthen Wall", 136:"Hagi Aibagawa-Tsuchihara Course",
137:"Hagi Former Matsumoto Village Course", 138:"Hagi Castle Town Course", 139:"Hagi Hamasaki Merchant Town Course",
140:OLDMAP+": Murozumi", 141:"Ito Hirobumi Memorial Museum Special Exhibition: Ito Hirobumi's Leadership",
142:"Tsukarigawa River Park (Fireflies)", 143:"Atata Olive Park", 144:"Italiano Hirao Olive Forest",
145:"Afternoon Tea at the Former Mori Family Residence", 146:OLDMAP+": Miyaichi (Easy Course Available)", 147:OLDMAP+": Tonomi",
148:OLDMAP+": Mitajiri", 149:"Amidaji Temple Stone Bath (Ancient Sauna) Experience", 150:OLDMAP+" (Limited Time): Former Sanyo Road, Hofu",
151:OLDMAP+": Kuwayama", 152:"Prayer-Bead Making at Suo Kokubunji Temple", 153:"Hofu Tenmangu Shrine Guided Tour by a Priest",
154:"Owaiko Laughing Ritual Experience (Hofu)", 155:"Make a Cypress-Bark Coaster at Eiunso", 156:"Hands-On Metal Casting in Hofu",
157:"Japanese Culture Experience at Eiunso (Heian Costume and Wagashi Making)", 158:"First Horse-Riding Experience (One Group a Day)",
159:"Sightseeing Taxi Plan: Hofu Quick Tour", 160:"Make Everyday Pottery at Tamanoya Kiln", 161:"Shiawasemasu Set Meal and Chill-Out Night at Hofu Tenmangu",
162:"Make Natural Salt in a Frying Pan", 163:"Traditional Sake Brewery Tour (Hofu)", 164:"Salt-Making Experience and Special Storehouse Opening",
165:"Indigo Dyeing Workshop with Lunch & Sweets", 166:"Tea Time at Mori Garden with Family-Crest Macarons",
167:"Private Experience at Daisenbo and Formal Worship at Hofu Tenmangu", 168:"Lord & Princess Lunch at Eiunso",
169:"Eiunso Night Illumination Walk with Dinner (Private)", 170:"Shiraishi Residence Storehouse Tour and Furoshiki Wrapping",
171:"Hofu Kimono and Matcha Experience at Hoshoan", 172:"Amulet Making at Suo Kokubunji Temple", 173:"Miso-Making Experience at Eiunso",
174:"Hofu Bicycle Sightseeing Ride", 175:"Make a Cypress-Bark Coaster and Art Frame at Eiunso", 176:"Hana no Sono Seaside Garden (Shinchikuji Green Space)",
177:"Kintaikyo Bridge Guided Tour with a Bridge Keeper", 178:"Kintaikyo Bridge Model-Making Experience (1/5 Scale)", 179:OLDMAP+": Iwakuni",
180:"Kintaikyo Bridge and Iwakuni Castle Town Stories by a Curator", 181:"Iwakuni Castle 400th Anniversary Ruins Tour",
182:"Kashiwabara Art Museum Talk by the Director", 183:"Kikko Shrine Buildings and Torii", 184:"Fuku no Kuni Yamaguchi Castle-Seal Tour",
185:"Maruta Village Forest Experience Center", 186:"Rape Blossom Fields around Minami-Kawachi Station", 187:"Iwakuni Kinriyama Guide Association",
188:OLDMAP+": Nagashima", 189:OLDMAP+": Murotsu", 190:OLDMAP+": Hanaoka (Easy Course Available)", 191:"Mushroom Farm Tour and Harvest",
192:"Set-Net Fishing Experience in the Seto Inland Sea", 193:"Sunset Yoga by the Seto Inland Sea", 194:"Kudamatsu Outdoor Cooking Experience",
195:"Trail Running and Hiking on Kasado Island", 196:"Coffee Brewing Experience", 197:"Kudamaru Figure-Making Experience",
198:OLDMAP+": Aokage", 199:"Omine Anthracite Coalfield Geo-Guide Tour", 200:"Akiyoshidai Trekking Tour (Scenic 3.5 km Course)",
201:OLDMAP+": Shuho", 202:"Perseid Meteor Shower Watching at Akiyoshidai", 203:"Aokage Village Geo-Guide Tour", 204:"Premium Onsen Stay Plan at Ontō (Nagato Yumoto)",
205:"Waterfall Purification at Mount Takataki", 206:OLDMAP+": Tawarayama (Easy Course Available)", 207:OLDMAP+": Senzaki",
208:OLDMAP+": Nagato Yumoto Onsen", 209:OLDMAP+": Kayoi", 210:"SOIL Nagatoyumoto (Sauna and Activity Center)", 211:OLDMAP+": Misumi",
212:"Kaneko Misuzu Guided Walk (with Kaneko Misuzu Memorial Museum)", 213:"Tawarayama Onsen Lunch Tour with a Local Guide", 214:OLDMAP+" (Limited Time): Akamagaseki Road North Route, Nagato",
215:"Afternoon Tea on a Cherry-Blossom Bridge", 216:"Omijima Nature Trail Guided Walk", 217:"Sea Kayaking in Yuya Bay",
218:"Sugamuta Park", 219:"Temple Lodging Vegetarian Meal and Mini Experiences", 220:"Nagato Yumoto Guide Association",
221:OLDMAP+": Asa", 222:"Farm Experience Tour (Hana no Umi)", 223:"Winery Tour (Nagayama Shuzo)", 224:"Niho no Ue Burial Mound",
225:"Sumiyoshi Shrine, Nagato's First Shrine", 226:OLDMAP+" (Limited Time): Akamagaseki Road (Hagi, Mine, Shimonoseki)", 227:OLDMAP+": Akamagaseki",
228:OLDMAP+": Chofu Castle Town", 229:"Hohoku History and Folk Museum (Taishokan)", 230:"Shimonoseki Sightseeing Course by Taxi",
231:OLDMAP+": Kawatana", 232:"Special Viewing of Sumiyoshi Shrine Main Hall (National Treasure)", 233:"Green Mall Shopping Street",
234:"Kaikyo Yume Tower View and Lunch Set", 235:"Naminori Johnny Beach House", 236:"Neohasu Hotel Book & Cafe",
237:"Shimonoseki Craft Beer at the Brewery", 238:"Tsunoshima Night Tour (Hotel Guests)", 239:OLDMAP+" (Limited Time): Akamagaseki Road Kitaura Route",
240:"Tsunoshima Sea Candle-Making Experience", 241:"Kaikyo Yume Tower Ticket with Meal Set", 242:"Fugu Sashimi Craftsman Class",
243:"SDGs Driftwood and Sea-Glass Crafts", 244:"SUP Experience at Ogushi Beach", 245:"Toyota Rent a Lease Yamaguchi Shin-Shimonoseki Station",
246:"Shimonoseki Tourist Guide Association", 247:"Tabunomine Park", 248:"Tsunoshima Yuyake-Imo Sweet Potato Roasting Tour", 249:"Kabeshima Cormorant Migration Site",
250:"Kanmon Nostalgic Straits Cruise (Japan Heritage)", 251:"Yu-Yu Plaza", 252:"Kanonkoto Seiryu Fes.", 253:OLDMAP+": Tokuyama",
254:"Mori Motonari Tooth Mausoleum", 255:OLDMAP+" (Limited Time): Nishiagenosho, Suo-Oshima", 256:"Suo-Oshima 88-Temple Island Pilgrimage",
257:"Suo-Oshima Volunteer Tourist Guide Association", 258:"Tokiwa Museum (World Plant Tour Greenhouse)", 259:OLDMAP+": Kami-Ube (Easy Course Available)",
260:OLDMAP+": Ogushi", 261:OLDMAP+": Fujiyama", 262:"Toyota Rent a Lease Yamaguchi Ube Hamamachi Office",
263:"Yamaguchi History Walk from Rurikoji Five-Storied Pagoda", 264:"Roadside Station Niho no Sato", 265:OLDMAP+": Yamaguchi",
266:OLDMAP+": Ogori", 267:"Ouchi Gozen: Muromachi-Era Hospitality Cuisine", 268:OLDMAP+": Sekishu Road, Yamaguchi",
269:OLDMAP+": Suzenji", 270:"Yamaguchi Sagi-ryu Kyogen Experience at Noda Shrine Noh Stage", 271:OLDMAP+": Hinaka Road, Yoshiki",
272:OLDMAP+": Hagi Okan Road (Hagi, Yamaguchi, Hofu)", 273:"Niho Ikkanno Wisteria", 274:OLDMAP+" (Limited Time): Omura (Suzenji), Yamaguchi",
275:"Kamura Isota Birthplace (Kikyoan)", 276:"Shogun Experience Tour", 277:"Nishi-Hobenzan and Higashi-Hobenzan Ridge Hiking Course",
278:"Shirakabe White-Wall Streetscape (Yanai Furuichi-Kanaya Preservation District)", 279:OLDMAP+": Shirakabe Town, Yanai",
280:OLDMAP+" (Limited Time): Iwakuni Tategahama, Yanai", 281:"Adelie Hoshi Park (Yanai Wellness Park)",
282:OLDMAP+" (Limited Time): Oze-Kaminoseki Road, Yanai", 283:"Shirakabe Town Tourist Guides", 284:OLDMAP+": Ohata",
285:"Yanai Seafood Street Stamp Rally", 286:OLDMAP+": Tozaki and Atsuki", 287:"DISCOVER WEST Hike: Shirakabe Town Yanai Walk with a Local Guide",
288:OLDMAP+": Hizumi",
}
